### ISSUE TITLE
package for Debian

### ISSUE THREAD

**Issue by stapelberg** [Debian/debiman#1]
To make deployment and usage easier, we should create a Debian package for debiman.

**Comment by stapelberg** [comment]
As a first step, I’ve created a git repository to hold the packaging: https://anonscm.debian.org/cgit/collab-maint/debiman.git/

**Comment by stapelberg** [comment]
Let’s postpone this until the setup has stabilized.

**Comment by anarcat** [comment]
shouldn't the debian package be here, in the upstream source? it's a native package after all... not sure why we would diverge in Debian.

furthermore, if this gets packaged, I wonder if we should ship the dman client with the package - maybe as a separate binary package, and if it should be re-written in go.

or should we, in the long run, go towards integrating dman functionality in man itself...

**Comment by stapelberg** [comment]
Ideally, debiman would not be specific to Debian, but also useful for other distributions (see also issue #56). Hence, I don’t think it should be a native package.

With regards to dman, I think the man package would be better — it’s already installed on many more machines, and is a better philosophical fit (it’s an implementation detail that manpages.debian.org is produced by debiman).

**Comment by bdrung** [comment]
What's the progress on the Debian package?

**Comment by anarcat** [comment]
dman is now shipped in the debian-goodies package. there is, as far as i know, no progress on packaging debiman itself.

**Comment by stapelberg** [comment]
That’s correct. @bdrung, I assume we’re still talking about your in-house instance of debiman. Would a package make your life easier?

**Comment by bdrung** [comment]
Yes. I prefer to have all code running in production come from Debian packages. That makes managing it easier (simpler salt states and faster to reproduce the instances). Bonus point: Having the package in Debian unstable.

**Comment by stapelberg** [comment]
Status update: pault.ag/go/archive and its dependency pault.ag/go/blobstore are now in the NEW queue, and pault.ag/go/debian has been updated.

Once all of these are in, I can package debiman itself.

**Comment by stapelberg** [comment]
Status update: debiman is now in the NEW queue.

**Comment by stapelberg** [comment]
Status update: debiman cleared the NEW queue. It should be picked up by the 07:52 UTC dinstall run, i.e. should be available on mirrors within a few hours.

Closing this issue. If there are problems with the packaging, please open specific issues.
