### ISSUE TITLE
dark themed browser issues

### ISSUE THREAD

**Issue by 532910** [Debian/debiman#117]
![image](https://user-images.githubusercontent.com/14617699/66272909-de4f4500-e877-11e9-8300-0989af69a281.png)

**Comment by stapelberg** [comment]
I don’t know if this is caused by the debian css we use, or our custom additions.

In either case, it’d be great if someone could send a pull request to fix this.

**Comment by 532910** [comment]
debian.org and packages.debian.org looks fine.
The fix is simple: both bg and fg colors should be defined together, or not defined at all.

**Comment by 532910** [comment]
https://security-tracker.debian.org issue:
https://salsa.debian.org/security-tracker-team/security-tracker/issues/4

**Comment by stapelberg** [comment]
You can find the CSS files either in this repository, and Debian-specific parts in https://salsa.debian.org/manpages-team/debian-assets

Please send a pull request/merge request.

**Comment by 532910** [comment]
https://github.com/Debian/debiman/pull/118

**Comment by 532910** [comment]
Looks fine now, thank you Michael!

**Comment by 532910** [comment]
While some pages looks fine now (like [plinth.1](https://manpages.debian.org/buster/freedombox/plinth.1.en.html), that I mentioned above in the PR, some other does not: [dpkg-divert.8](https://manpages.debian.org/wheezy/dpkg/dpkg-divert.8.en.html), [dpkg.1](https://manpages.debian.org/wheezy/dpkg/dpkg.1.en.html) or [error page](https://dyn.manpages.debian.org/jump?suite=buster&binarypkg=manpages-dev&section=3&language=en&q=404)

**Comment by 532910** [comment]
Is it my fault or they weren't re-rendered?

**Comment by stapelberg** [comment]
> While some pages looks fine now (like [plinth.1](https://manpages.debian.org/buster/freedombox/plinth.1.en.html), that I mentioned above in the PR, some other does not: [dpkg-divert.8](https://manpages.debian.org/wheezy/dpkg/dpkg-divert.8.en.html), [dpkg.1](https://manpages.debian.org/wheezy/dpkg/dpkg.1.en.html) 

You’re linking to very old manpages (wheezy) which will not be re-rendered. They are available only so that old URLs don’t break.

The current suites are: stable, stable-backports, testing, unstable, experimental

> or [error page](https://dyn.manpages.debian.org/jump?suite=buster&binarypkg=manpages-dev&section=3&language=en&q=404)

These just needed a server restart and now serve the updated stylesheet.

**Comment by 532910** [comment]
Haa, ok!
