### ISSUE TITLE
brace at the end of the link

### ISSUE THREAD

**Issue by 532910** [Debian/debiman#121]
https://manpages.debian.org/unstable/slapd/slapd.plugin.5.en.html
points to [http://www.openldap.org/doc/admin/)](http://www.openldap.org/doc/admin/\)) but the correct link is without brace at the end:[http://www.openldap.org/doc/admin/](http://www.openldap.org/doc/admin/)

slapd.plugin.5:
```Man
.SH SEE ALSO 
.BR slapd (8),
.LP
"OpenLDAP Administrator's Guide" (http://www.OpenLDAP.org/doc/admin/)
.SH ACKNOWLEDGEMENTS
.so ../Project
```

**Comment by 532910** [comment]
https://www.openldap.org/software/man.cgi?query=slapd.plugin renders is correctly

**Comment by stapelberg** [comment]
https://github.com/Debian/debiman/blob/fc8252157877b4f57b1598fe2e7d1a5cbe438e7f/internal/convert/convert.go#L158 is where we find xrefs and URLs. The code should be updated to exclude `)` (and probably others, but I don’t have an exhaustive list handy) from URLs.

Let me know if you want to send a PR which changes the code (and the [corresponding test](https://github.com/Debian/debiman/blob/fc8252157877b4f57b1598fe2e7d1a5cbe438e7f/internal/convert/convert_test.go#L243))

**Comment by stapelberg** [comment]
I deployed a new version with the fix and started a re-render of the entire archive.

It’ll be a while before it’s done and live, though: expect pages to be fixed within the next few days.
