### ISSUE TITLE
apt-secure(8)

### ISSUE THREAD

**Issue by borg2borg** [Debian/debiman#122]

**Comment by borg2borg** [comment]
Hi, I recently flashed debian onto a Snapdragon and RPi4, while doing an apt-get update I received the following error:

N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for detials..

That's where I stand now, I checked out the error via a quick search and found this... please help.

**Comment by stapelberg** [comment]
You’re in the wrong place. This repository is about a program that generates manual pages.

Please see https://www.debian.org/support instead

**Comment by borg2borg** [comment]
Thanks for the direction, much appreciated.
