### ISSUE TITLE
Travis-ci: error while enabling ppc64le build along with amd64

### ISSUE THREAD

**Issue by sanjay-cpu** [Debian/debiman#123]
Hi,

I am enabling ppc64le build on travis-ci and added the arch:ppc64le along with amd64 in .travis.yml. But it's failing for all of them(ppc64le and amd64 both).
I am getting below error: 

cmd/debiman/main.go:18:2: use of internal package github.com/Debian/debiman/internal/bundled not allowed
cmd/debiman/main.go:19:2: use of internal package github.com/Debian/debiman/internal/commontmpl not allowed
cmd/debiman/render.go:22:2: use of internal package github.com/Debian/debiman/internal/convert not allowed
cmd/debiman/download.go:22:2: use of internal package github.com/Debian/debiman/internal/manpage not allowed
cmd/debiman/writeindex.go:7:2: use of internal package github.com/Debian/debiman/internal/proto not allowed
cmd/debiman/download.go:23:2: use of internal package github.com/Debian/debiman/internal/recode not allowed
cmd/debiman/render.go:24:2: use of internal package github.com/Debian/debiman/internal/sitemap not allowed
cmd/debiman/download.go:24:2: use of internal package github.com/Debian/debiman/internal/write not allowed

For full error log please see the link: https://travis-ci.com/github/sanjay-cpu/debiman/builds/185829499

Please have a look into this.

Thanks !!

**Comment by stapelberg** [comment]
You cannot just copy a Go repository without changing the import paths within the repository.

String-replace github.com/Debian/debiman with github.com/sanjay-cpu/debiman and it should work.

**Comment by sanjay-cpu** [comment]
Ok, Thanks
