### ISSUE TITLE
nftables.Nftables() class instance is unusable if ONE call to json_cmd() fails 

### ISSUE THREAD

**Issue by remi-cbd** [Debian/debiman#126]
In a python3 program, using the nftables python module

Trying to get a Table on an empty Ruleset returns an error, no problem.
Trying to call another function on the same nftables.Nftables class instance after a function which returns an error (rc != 0) is not possible, any other call to json_cmd() just fails after the first error.

Here is a script showing the error

[testNFTABLES.txt](https://github.com/Debian/debiman/files/5926400/testNFTABLES.txt)

**Comment by stapelberg** [comment]
You’re in the wrong place. This repository is about debiman, a manual page (documentation) static site generator.

You seem to be looking for an nftables-related repository instead.

**Comment by remi-cbd** [comment]
You are right, i followed the FAQ link in bottom of this page :
https://manpages.debian.org/unstable/libnftables1/libnftables-json.5.en.html
