### ISSUE TITLE
paragraphs are indented differently

### ISSUE THREAD

**Issue by FranklinYu** [Debian/debiman#128]
Under each heading, the first paragraph isn’t indented; starting from the second they are indented by 2 characters. Expected:

```plain
1st paragraph

2nd paragraph

3rd paragraph
```

Actual:

```plain
1st paragraph

  2nd paragraph

  3rd paragraph
```

This seems to affect every page. Example: [adduser(8)](https://manpages.debian.org/buster/adduser/adduser.8.en.html)

**Comment by stapelberg** [comment]
Just verified: this issue is the same as https://github.com/Debian/debiman/issues/116, which is already fixed at mandoc HEAD, but there hasn’t been a new release since.

**Comment by FranklinYu** [comment]
By “a new release” you mean `debiman` or `mandoc`?

**Comment by stapelberg** [comment]
Yes, I was referring to mandoc. I don’t think mandoc’s release is coupled to OpenBSD in any way.

@ischwarze can you answer this? :)
