### ISSUE TITLE
launch

### ISSUE THREAD

**Issue by stapelberg** [Debian/debiman#13]
This checklist tracks items that need to be fulfilled before we can launch:

* [x] set up git mirror on alioth: https://anonscm.debian.org/cgit/users/stapelberg/debiman.git/
    * [x] `git clone --mirror https://github.com/Debian/debiman/`
    * [x] crontab: `7 * * * * (cd /git/users/stapelberg/debiman.git && git fetch --quiet -p origin && git gc --quiet)`
* [x] set up git repository for debian assets on alioth (pending permissions issue): https://anonscm.debian.org/cgit/srv-manpages/debian-assets.git
    * [x] `sudo -u manpages git -c http.sslCAInfo=/etc/ssl/ca-debian/ca-certificates.crt clone https://anonscm.debian.org/git/srv-manpages/debian-assets.git /srv/manpages.debian.org/debiman/debian-assets`
    * [x] `sudo -u manpages git config --local --add http.sslCAInfo /etc/ssl/ca-debian/ca-certificates.crt`
* [x] get mandoc into jessie-backports
    * [x] have mandoc installed on manziarly (pending: https://rt.debian.org/Ticket/Display.html?id=6538)
* [x] get go 1.7 into jessie-backports
    * [x] have go 1.7 installed on manziarly (pending: https://rt.debian.org/Ticket/Display.html?id=6538)
        * [x] set up a group-writeable checkout of debiman so that jfs et al. can do maintenance when necessary
            * [x] `mkdir -p /srv/manpages.debian.org/debiman/gopath`
            * [x] `chmod -R g+ws /srv/manpages.debian.org/debiman`
            * [x] `setfacl -m "default:group::rwx" /srv/manpages.debian.org/debiman`
            * [x] add GOPATH environment variable to shell setup
* [x] verify debiman compiles with go 1.7
* [x] successfully run debiman
* [x] touch .nobackup in the output directory, because re-generating is simpler than restoring from backup
* [x] implement index swapping in debiman-auxserver (possibly triggered by SIGHUP, or use restart for now)
* [x] change apache configuration to serve both, the current manpages.debian.org and the debiman output
* [x] verify all current URLs are covered by redirects
    * [x] `/man/<section>/<name>`
    * [x] `/man<section>/<name>`
    * [x] `/<lang>/man<section>/<name>`
    * [x] `/man/<suite>/<lang>/<section>/<name>`
    * [x] `/man/<suite>/<section>/<name>`
    * [x] `/<section>/<name>`
    * [x] `/man/<lang>/<name>`
    * [x] `/man/<name>`
* [x] set up debiman-auxserver
* [x] set up a cronjob to update the output (with injected assets), using `flock`
* [x] prepare launch announcement email/blog post
* [x] get sign-off from jfs and anarcat w.r.t switching the index.html page and apache config, thereby publically launching
    * [x] Change `<Directory>` directive to apply for the entire vhost
    * [x] add `ErrorDocument 404 /auxserver/%{REQUEST_URI}?%{QUERY_STRING}`
    * [x] remove `/srv/manpages.debian.org/www/.htaccess`
    * [x] change `robots.txt` to only Disallow /cgi-bin/
* [x] update https://wiki.debian.org/manpages.debian.org

After a few days:
* [x] de-activate the CGI script

**Comment by anarcat** [comment]
i see that https://rt.debian.org/Ticket/Display.html?id=6538 is resolved, which should clear the last two checkboxes here. i would do it myself and close this, but i do not have access (https://github.com/Debian/README.Debian/issues/5). :)
