### ISSUE TITLE
Latest Debian (debian-10.9.0-amd64-netinst.iso) does not include can-j1939 module by default

### ISSUE THREAD

**Issue by ManishKakra** [Debian/debiman#130]
Hello,
I have tried below image for virtual box environment and it does not seem to include the can-j1939 modules by default.
debian-10.9.0-amd64-netinst.iso
More details on J1939 is here https://www.kernel.org/doc/html/latest/networking/j1939.html

In order to use this, module I will have to rebuild the kernel with can-j1939 module included with below steps:
https://github.com/linux-can/can-utils/blob/master/can-j1939-install-kernel-module.md

Is that something that was supported to be by default in recent kernel images ?
Is there any other Debian image version that includes it by default?

Please suggest. Thank you in advance.

Thanks,
Manish K

**Comment by stapelberg** [comment]
You’re in the wrong place. This is a repository for an internal program used in Debian.

 Please see https://www.debian.org/support instead.
