### ISSUE TITLE
updates for Debian bullseye release

### ISSUE THREAD

**Issue by pabs3** [Debian/debiman#131]
Debian bullseye has released as the new stable and Debian bookworm is the new testing, so the [hardcoding](https://wiki.debian.org/SuitesAndReposExtension#manpages.debian.org) of Debian release information needs to be updated in debiman and on manpages.debian.org.

**Comment by stapelberg** [comment]
Change committed. Will deploy to manpages.d.o tomorrow.

**Comment by stapelberg** [comment]
Re-render done, and the pages generated by version debiman 38831b8 seem to be synced to the static serving infrastructure now.
