### ISSUE TITLE
The debiman logo does not render very well with github dark theme

### ISSUE THREAD

**Issue by nthykier** [Debian/debiman#142]
Hi,

I noticed that the debiman logo is hard to "see" properly in the github dark theme mode.

![debiman-logo-dark-theme](https://user-images.githubusercontent.com/429402/167285006-7e891f59-5ec9-4891-ab8c-83f120312a61.png)

To reproduce, go to https://github.com/settings/appearance and select a dark theme mode.  Then go to https://github.com/Debian/debiman/ and check the logo shown in the `README.md` section.

**Comment by stapelberg** [comment]
Thanks, should be fixed once GitHub’s cache expires
