### ISSUE TITLE
Reporting a typo in the manpage of lft command

### ISSUE THREAD

**Issue by zyabxwcd** [Debian/debiman#158]
Hi, I was searching for the manpage of "**lft**" command when I landed here https://manpages.debian.org/testing/lft/lft.8.en.html. 
There is a typo in the spelling of 'service' when explaining the -I flag, in particular when mentioning the full form of ToS. I tried to find a way to fix it myself by opening a PR but I think I am wrong in thinking that this is the repository where it can be fixed, thus reporting it as an issue for some guidance or simply logging the issue.

Thanks

**Comment by stapelberg** [comment]
> I tried to find a way to fix it myself by opening a PR but I think I am wrong in thinking that this is the repository where it can be fixed

Correct, this is the wrong repository.

In the manpage you read, scroll to the very bottom:

> To report bugs, send e-mail to <lft@oppleman.com>

I suggest you send an email. 

(I checked on https://packages.debian.org/sid/lft that lft.8 is part of the lft_3.91.orig.tar.gz archive, so the manpage is part of the software, not added by Debian.)
