### ISSUE TITLE
Could not load auxserver index

### ISSUE THREAD

**Issue by KenSharp** [Debian/debiman#160]
[Following the instructions](https://github.com/Debian/debiman) I'm immediately hit by a failure I don't know how to fix:

```
# apt install golang mandoc
# go install github.com/Debian/debiman/cmd/...@main
# ~/go/bin/debiman -serving_dir=/root/man -only_render_pkgs=qelectrotech,i3-wm,cron
<snip>
2023/07/26 18:30:24 main.go:215: extracting manpages: downloading testing/src:libtext-wrapi18n-perl 0.06-10: archive download: parsing time "" as "Mon Jan _2 15:04:05 2006": cannot parse "" as "Mon"
```

Is this error is causing everything else to fail?

```
# ~/go/bin/debiman-minisrv -serving_dir=/root/man
2023/07/26 18:23:01 Could not load auxserver index: open /root/man/auxserver.idx: no such file or directory
```

Indeed, `auxserver.idx` does not exist.

[debiman.log](https://github.com/Debian/debiman/files/12176254/debiman.log)

Note: Running as root because I was in a chroot.  Same thing happens for a normal user.

**Comment by stapelberg** [comment]
> Is this error is causing everything else to fail?

Yes. In the success case, the program ends with a log like this:

```
[…]
2023/07/26 21:57:48 rendermanpage.go:322: rendering "/home/michael/man/testing/i3-wm/i3-with-shmlog.1.en.html.gz"
2023/07/26 21:57:56 main.go:138: Rendered all manpages, writing index
2023/07/26 21:57:56 main.go:144: Writing debiman-auxserver index to "/home/michael/man/auxserver.idx"
total number of packages: 17236
packages extracted:       17236
packages deleted:         0
manpages rendered:        52
total manpage bytes:      98284
total HTML bytes:         1343980
auxserver index bytes:    8060943
wall-clock runtime (s):   206
```

> ```
> 2023/07/26 18:30:24 main.go:215: extracting manpages: downloading testing/src:libtext-wrapi18n-perl 0.06-10: archive download: parsing time "" as "Mon Jan _2 15:04:05 2006": cannot parse "" as "Mon"
> ```

Weird! I just ran debiman with an empty ~/man and I did not encounter the error you got.

Can you try running with `--remote_mirror=http://mirror1.infomaniak.com/`, for example, to rule out any funny apt-cacher-ng business? Or maybe your internet connection is somehow proxied or interfered with?

**Comment by KenSharp** [comment]
That did it! acng, you got me again!

Sorry for the noise.
