### ISSUE TITLE
Bad lolcat → LOLCAT redirect

### ISSUE THREAD

**Issue by jwilk** [Debian/debiman#161]
<https://manpages.debian.org/lolcat.6> redirects to <https://manpages.debian.org/bookworm/filters/LOLCAT.6.en.html> instead of <https://manpages.debian.org/bookworm/lolcat/lolcat.6.en.html>.

**Comment by stapelberg** [comment]
I’ve pushed commit https://github.com/Debian/debiman/commit/adb0794ba69307b751e2772bead7d0d6cd0307d0, with which this redirect happens to go to the lolcat package. It should be effective tomorrow or so.

**Comment by crpb** [comment]
Now https://manpages.debian.org/LOLCAT redirects to https://manpages.debian.org/bookworm/lolcat/lolcat.6.en.html instead of https://manpages.debian.org/bookworm/filters/LOLCAT.6.en.html
:see_no_evil:

**Comment by stapelberg** [comment]
Yeah, the redirects aren’t case-sensitive. 

I would have said “contributions welcome”, but changing the code is only part of the puzzle. Keeping an eye on the (apache rewrite map based) deployment and being available for troubleshooting / fixes is the more involved part, and I don’t have time for that in the upcoming weeks.
