### ISSUE TITLE
Can't Entroll Finger Print in Ubudu 22.04 

### ISSUE THREAD

**Issue by unaisshemim** [Debian/debiman#169]
when i try to run this on Terminal
`fprintd-enroll`
 This error shows error :
`Impossible to enroll: GDBus.Error:net.reactivated.Fprint.Error.NoSuchDevice: No devices available
`
### Note-Can Any Body Tell How to use FingerPrint Scanner in ubuntu as Screen Lock .
[Reference](https://askubuntu.com/a/1429056/1283513)

**Comment by stapelberg** [comment]
You are in the wrong place.

This GitHub repository is about software development of the manpage archive converter behind manpages.debian.org.

Take a look at https://ubuntu.com/support/community-support instead

**Comment by unaisshemim** [comment]
thank you
