### ISSUE TITLE
Update docs for db_installdocs to explain how empty files are treated

### ISSUE THREAD

**Issue by stevegrossmongodb** [Debian/debiman#174]
I discovered that db_installdocs ignores empty files ([code](https://github.com/Debian/debhelper/blob/master/dh_installdocs#L321)). Can y'all update the [docs](https://manpages.debian.org/testing/debhelper/dh_installdocs.1.en.html) to note this?

**Comment by stapelberg** [comment]
Sorry, you’re in the wrong place. This project is the generation pipeline behind the website manpages.debian.org, but you’re looking for debhelper or some debhelper add-on.

**Comment by stevegrossmongodb** [comment]
Aha, sorry, thanks for the followup!
