### ISSUE TITLE
Add the POSIX manpages to debiman

### ISSUE THREAD

**Issue by n-peugnet** [Debian/debiman#176]
I thought it could be interesting to be able to easily alternate between the Linux and POSIX (from [manpages-posix](https://packages.debian.org/sid/manpages-posix) and from [manpages-posix-dev](https://packages.debian.org/sid/manpages-posix-dev)) versions of a manual page directly in debiman.

As freebsd and plan9 variants are already built (ex: [read.2](https://manpages.debian.org/read.2freebsd.en.html)), wouldn't it simply be a matter of adding `"non-free"` to this list? https://github.com/Debian/debiman/blob/4afba3a1fef8fc4215d59c13926082ac1001a987/cmd/debiman/getcontents.go#L184

But I guess there is a reason why it has been excluded until now. Maybe an exception for these packages could be added?

**Comment by stapelberg** [comment]
Thanks for your suggestion.

The reason why non-free is excluded is because the software (and documentation) in non-free is not licensed to be distributed without restrictions. (This is why they are in non-free.) Hence, we cannot (generally) serve them on manpages.d.o.

(Here’s a prominent example that often surprises people: GCC’s documentation is non-free: https://unix.stackexchange.com/q/287075/181634)

**Comment by n-peugnet** [comment]
I understand that such material cannot be distributed in the main (or contrib) component.
But wouldn't it be possible to add exceptions for packages that we know, allow at least their documentation to be redistributed or published?

For instance, the [manpages-posix's copyright file](https://metadata.ftp-master.debian.org/changelogs/non-free/m/manpages-posix/manpages-posix_2017a-2_copyright) states that:

> Redistribution of this material is permitted so long as this notice and the corresponding notices within each POSIX manual page are retained on any distribution, and the nroff source is included. Modifications to the text are permitted so long as any conflicts with the standard are clearly marked as such in the text.

**Comment by stapelberg** [comment]
> But wouldn't it be possible to add exceptions for packages that we know, allow at least their documentation to be redistributed or published?

On a technical level, sure. But the software doesn’t currently support that.

If you’re interested in contributing support for filtering a distribution like you suggest, feel free. Are you also interested in maintaining the list of permitted packages? 

(I don’t currently plan to spend more time on manpages.d.o, as I retired from Debian years ago: https://michael.stapelberg.ch/posts/2019-03-10-debian-winding-down/)

**Comment by n-peugnet** [comment]
> > But wouldn't it be possible to add exceptions for packages that we know, allow at least their documentation to be redistributed or published?
> 
> On a technical level, sure. But the software doesn’t currently support that.
> 
> If you’re interested in contributing support for filtering a distribution like you suggest, feel free. Are you also interested in maintaining the list of permitted packages?

Thank you for your answer, I might try to add this feature but not right now, then I would indeed be interested in maintaining such a list.

> (I don’t currently plan to spend more time on manpages.d.o, as I retired from Debian years ago: https://michael.stapelberg.ch/posts/2019-03-10-debian-winding-down/)

I understand, I already read this post by the way, it was an interesting read.
