### ISSUE TITLE
indentation in code examples is lost

### ISSUE THREAD

**Issue by reinerh** [Debian/debiman#21]
Some manpages have source code examples, like [scanf(3)](https://manpages.debian.org/jessie/manpages-dev/scanf.3.en.html).
The generated HTML page loses the indentation, which doesn't look very nice.

**Comment by stapelberg** [comment]
Thanks for the report.

Manpage rendering is done by [mandoc(1)](https://manpages.debian.org/testing/mandoc/mandoc.1.en.html).

The indentation is present when rendering to stdout:
```
$ curl https://manpages.debian.org/jessie/manpages-dev/scanf.3.en.gz | mandoc
[…]
EXAMPLE
       To use the dynamic allocation conversion specifier, specify m as a
       length modifier (thus %ms or %m[range]).  The caller must free(3) the
       returned string, as in the following example:

           char *p;
           int n;
```

…but not when rendering to HTML:
```
$ curl https://manpages.debian.org/jessie/manpages-dev/scanf.3.en.gz | mandoc -Thtml
[…]
<h1>EXAMPLE</h1> To use the dynamic allocation conversion specifier, specify <b>m</b> as a length modifier (thus <b>%ms</b> or  <b>%m[</b><i>range</i><b>]</b>). The caller must <b>free</b>(3) the returned string, as in the following example:<br/>
<div class="spacer">
</div>
<br/>
char *p;<br/>
int n;<div class="spacer">
</div>
<br/>
errno = 0;<br/>
n = scanf(&quot;%m[a-z]&quot;, &amp;p);<br/>
if (n == 1) {<br/>
    printf(&quot;read: %s\n&quot;, p);<br/>
    free(p);<br/>
} else if (errno != 0) {<br/>
    perror(&quot;scanf&quot;);<br/>
} else {<br/>
    fprintf(stderr, &quot;No matching characters\n&quot;);<br/>
}<br/>
<br/>
<div class="spacer">
</div>
As shown in the above example, it is necessary to call <b>free</b>(3) only if the <b>scanf</b>() call successfully read a string.</div>
<div class="section">
```

This is reproducible with the mandoc version in Debian testing (1.13.3-3), and with a CVS checkout from yesterday.

Would you like to report this issue upstream? If you’d prefer, I could do that for you.
See http://mdocml.bsd.lv/ for the upstream website.

**Comment by reinerh** [comment]
Thanks for clarifying that the pages are generated with mandoc.
I just had a look at the current upstream version and noticed that this is already known and on their [TODO list](http://mdocml.bsd.lv/cgi-bin/cvsweb/TODO.diff?r1=1.216&r2=1.217&f=h).

**Comment by stapelberg** [comment]
This has been fixed upstream. Re-opening this issue to track the rollout of the new version to manpages.d.o.

**Comment by stapelberg** [comment]
This is now live.
