### ISSUE TITLE
Support man.freebsd.org's syntax

### ISSUE THREAD

**Issue by danielshahaf** [Debian/debiman#24]
FreeBSD's corresponding service supports passing the section as:

http://man.freebsd.org/printf/3 

Would you consider supporting the same URL structure?  (If it's unambiguous...)   The advantage over http://manpages.debian.org/printf%283%29 is that neither shell-quoting (for the `(` `)`) nor percent-encoding are required, and over http://manpages.debian.org/printf.3 that (a) man pages with dots in their names would work unambiguously (think rsyncd.conf(5)), (b) same URL structure across platforms means fewer things to concern one's brain with.

Thanks for restoring the service!

**Comment by stapelberg** [comment]
Note that manpages with dots in them already work, the redirector is smart enough :).

I’ll take a look at whether we can also implement `/<name>/<section>` unambiguously.

**Comment by danielshahaf** [comment]
Thanks!
