### ISSUE TITLE
search when viewing a manpage should search within the same distribution as current manpage

### ISSUE THREAD

**Issue by fsateler** [Debian/debiman#25]
Say I am looking at https://manpages.debian.org/unstable/systemd/systemd.directives.7.en.html, that is the unstable version of a manpage. Then I decide to search for `systemctl`. The result is https://manpages.debian.org/jessie/systemd/systemctl.1.en.html , the stable version. I think the result should come (if possible) from the same distribution.

**Comment by stapelberg** [comment]
Fair point! We could totally use the referrer to see where people are coming from and use that to fill in the blanks.

**Comment by stapelberg** [comment]
It has been pointed out that a cleaner solution is to include the suite in the form, because referers make it harder to cache the redirects. I’ll look into that.

**Comment by fsateler** [comment]
@stapelberg indeed, adding the parameter to the form sounds like a better solution. Thanks!

**Comment by stapelberg** [comment]
This will be live with the next re-render (within the next few days).

**Comment by fsateler** [comment]
Thanks!!

Saludos,
Felipe Sateler
