### ISSUE TITLE
text overlaps panels with qutebrowser 0.9.0

### ISSUE THREAD

**Issue by stapelberg** [Debian/debiman#26]
reported in https://www.reddit.com/r/linux/comments/5oqrb9/show_rlinux_manpagesdebianorg_has_been_modernized/dclizgd/

**Comment by The-Compiler** [comment]
qutebrowser dev here - this only happens with the QtWebKit backend, which is based on a somewhat dated WebKit. It works fine with the (WIP) QtWebEngine backend which is based on Chromium.

**Comment by stapelberg** [comment]
@The-Compiler Thanks for chiming in! Is there anything we should fix on our end to make this work in the QtWebKit backend as well, or would you recommend we don’t bother?

**Comment by The-Compiler** [comment]
Your choice really - I don't know CSS very well so I can't comment on how easy a fix would be. FWIW there are some other minimal browsers around which are likely affected as well.

**Comment by stapelberg** [comment]
I think commits https://github.com/Debian/debiman/commit/3cf076f78af686b380ca1a1666b403d5feed5ea4 and https://github.com/Debian/debiman/commit/855791a69302e310af275eb7707cf3415cb8b07c made things better for qutebrowser as a side-effect. At least, I cannot reproduce the issue in qutebrowser, and on browsershots.org every browser looks reasonable.

Closing. Please reopen if there’s still something we need to fix.
