### ISSUE TITLE
"table of contents" panel header styling broken on firefox-esr

### ISSUE THREAD

**Issue by emorrp1** [Debian/debiman#28]
Currently, e.g. [openssl](http://web.archive.org/web/20170118215939/https://manpages.debian.org/jessie/openssl/openssl.1ssl.en.html) has the red border just around the "table of contents" text, rather than the whole box. This appears to be because that panel uses `details` and `summary` tags rather than the `div` structure of the other panels.

Great upgrade!

**Comment by stapelberg** [comment]
Could you attach a screenshot of what you see please? This is what I see (and what was intended):

collapsed: [2017-01-18-230348_731x625_scrot](https://cloud.githubusercontent.com/assets/55506/22084960/6bd59d60-ddd2-11e6-82db-7735bbf2263e.png)

expanded: [2017-01-18-230356_728x933_scrot](https://cloud.githubusercontent.com/assets/55506/22084969/70a0b49c-ddd2-11e6-8786-97d46619f3b3.png)

**Comment by stapelberg** [comment]
Also, which browser version and operating system do you use?

**Comment by emorrp1** [comment]
Sorry, I forgot archive.org doesn't have screenshots, archive.is does indeed [display as intended](http://archive.is/FTUVt/image).

I'm using firefox-esr on Jessie, 45.6.0esr-1~deb8u1 and I created a fresh profile to double check my addons weren't affecting it:
![screenshot from 2017-01-18 22 20 48](https://cloud.githubusercontent.com/assets/71895/22085554/68b38a44-ddcc-11e6-91bc-0fec65773b98.png)

**Comment by emorrp1** [comment]
It appears that the `details` expandable behaviour was only added in [Firefox 47](http://caniuse.com/#feat=details).

Comparing the styling with Chromium inspector, the following CSS is listed as "user agent stylesheet" and make it look like the other panels without affecting chromium:

[screenshot from 2017-01-18 22:48:23](https://cloud.githubusercontent.com/assets/71895/22086339/3c313864-ddd0-11e6-9a0c-924b21d32538.png)

```
summary, details {
  display: block;
}
```

**Comment by stapelberg** [comment]
Thanks for the details. I can reproduce the issue with firefox-esr, and indeed adding the `display: block` seems to fix this issue. The fix will be live once we re-render the repository (within the next 24h).
