### ISSUE TITLE
Hard links are not extracted from Debian packages

### ISSUE THREAD

**Issue by andrewshadura** [Debian/debiman#31]
If I type `ip` into the ‘Directly jump to any manpage:’ box, I’m redirected to https://manpages.debian.org/jessie/freebsd-manpages/ip.4freebsd.en.html and that page says 404.

**Comment by stapelberg** [comment]
Thanks for the report, will look into that in a bit.

**Comment by stapelberg** [comment]
Turns out that page is a hardlink, and we currently only extract regular files and symlinks:

```
$ ar x ../freebsd-manpages_10.1\~RC1-1_all.deb
$ tar tf data.tar.xz -v | grep 'man4/ip\.'
hrw-r--r-- root/root         0 2014-10-04 13:45 ./usr/share/man/man4/ip.4freebsd.gz link to ./usr/share/man/man4/rawip.4freebsd.gz
```

Will fix this in a bit.

**Comment by stapelberg** [comment]
This is now fixed, but will only be live after the next re-download, which I’ll trigger within the next few days.
