### ISSUE TITLE
Please strip <> from the URL if it in <url> format

### ISSUE THREAD

**Issue by sebastianas** [Debian/debiman#38]
Certain man pages put an URL in braces like:

> in the source distribution or at
> \<https://www.openssl.org/source/license.html>.

which is from [SSL.7ssl.en](https://manpages.debian.org/unstable/openssl/SSL.7ssl.en.gz).
The [rendered](https://manpages.debian.org/unstable/openssl/SSL.7ssl.en.html) version adds the closing > to the URL so you can't click on it.

**Comment by stapelberg** [comment]
The fix will be live after the next re-render (within the next few days).
