### ISSUE TITLE
Have a way to search and show manpages from various suites 

### ISSUE THREAD

**Issue by shirishag75** [Debian/debiman#50]
The current way to view a manpage from a suite other than stable requires quite a bit of expertise. Having a drop-down list of the various suites should make it easier.

**Comment by stapelberg** [comment]
Not sure I follow. On e.g. https://manpages.debian.org/jessie/w3m/w3m.1.en.html, selecting the manpage from another suite is just a click away, see following screenshot. Can you clarify why this doesn’t work for you?

![2017-01-24-215717_687x739_scrot](https://cloud.githubusercontent.com/assets/55506/22266390/1b9ed692-e280-11e6-9be7-ef0d5a515156.png)

**Comment by shirishag75** [comment]
umm.. which mailing list please ? btw, my bad. Didn't see that. Now, only if I could set a suite other than jessie as default, it would be cool.

**Comment by stapelberg** [comment]
Once you navigate to a suite, that suite will be used in further navigations via the search form. You can also prefix your query with the desired suite (in the search form, when using manpages as a search engine and when using URLs).
