### ISSUE TITLE
There should be a diff visualizer for manpages in two or more suites 

### ISSUE THREAD

**Issue by shirishag75** [Debian/debiman#51]
It would be great/fantastic if we had a manpage diff output facility. Meld is a utility which does similar function except in meld i have to provide the names which need to be parsed. Look forward to having such a service.

**Comment by stapelberg** [comment]
The best way to accomplish this is to download the manpages in question (ctrl-s in your browser, most likely) and open them in meld (or any other diffing tool of your choice).

You could automate the process with a little script/program if you do this often. Issue #49 might come in handy in that case.

In case your diff tool of choice does not support HTML, you can render a text version of each manpage locally (until we also provide pre-rendered text versions), using e.g.:

```
curl https://manpages.debian.org/jessie/w3m/w3m.1.en.gz | man /dev/stdin
```

Hope that helps.
