### ISSUE TITLE
man git rebase equivalent

### ISSUE THREAD

**Issue by mcepl** [Debian/debiman#58]
man (at least as I have it here on Fedora) is able to find two-word-named manpages, e.g., ``man git rebase`` works. It doesn't for m.d.o. where I have to use ``git-rebase`` instead.

**Comment by stapelberg** [comment]
Thanks for the report. Indeed, when presented with multiple arguments, man(1) will first join them by dashes, then underscores, and then treat them as separate pages. I’ll see about implementing the same behavior.
