### ISSUE TITLE
add a note where to report problems

### ISSUE THREAD

**Issue by nmartensen** [Debian/debiman#61]
When reading a manpage, it may happen that readers will notice problems. These might be related to broken manpage display, but can also be errors in the content like wrong descriptions or simple typos.

It would be nice to have a hint on each page on where/how to report problems.

**Comment by stapelberg** [comment]
There are 3 different places where problems might need to be reported:

1. If the manpage renders correctly in some manpage viewers, but not on manpages.debian.org, this might likely be a limitation/bug with mdocml (the renderer we use). Report at mdocml.
2. If the manpage contains wrong content, and was added by the Debian package maintainer, report at the Debian bug tracker.
3. If the manpage contains wrong content and comes from the upstream software, report at the upstream bug tracker.

I’m happy to add this information to our documentation (I think we might have enough questions to re-instate the FAQ section on manpages.debian.org by now), but I don’t see how we could distinguish the cases from each other, i.e. we can’t distill it into a simple “click here to report a problem” link.

What do you think?

**Comment by nmartensen** [comment]
"Noticed a problem? Please check our FAQ." - I like this, good idea.

**Comment by anarcat** [comment]
maybe the FAQ link could just point to the wiki that way anyone could edit it easily? IIRC, the site-specific assets are not here, and it may be confusing for people to edit/report issues against the FAQ...

**Comment by anarcat** [comment]
i created a "faq" branch on the debian-assets repository:

https://anonscm.debian.org/git/srv-manpages/debian-assets.git/log/?h=faq

i haven't merged it because i'm not sure it was actually wanted here. let me know if i should just merge/push [the result](https://anonscm.debian.org/git/srv-manpages/debian-assets.git/tree/faq.tmpl?h=faq). there are other issues solved by that branch too, btw. see #76 and #52.

**Comment by stapelberg** [comment]
See my reply in https://github.com/Debian/debiman/issues/76#issuecomment-298753795

**Comment by anarcat** [comment]
i have merged the faq branch as is, which should clearly document how to do things here. this will show up once a full rebuild is triggered, see #76 for followup.
