### ISSUE TITLE
OpenSearch suggestions

### ISSUE THREAD

**Issue by bucklereed** [Debian/debiman#65]
[OpenSearch suggestions](http://www.opensearch.org/Specifications/OpenSearch/Extensions/Suggestions/1.1) are a way of offering autocomplete suggestions to the browser. In the context of manpages, they'd be very handy for selecting the correct section or package in a single hop, rather than navigating to one of the candidates and then looking at the other sections/conflicting packages boxes.

A strawman of what I would like:

cron -> ["cron", ["cron.8", "cron/crontab.5", "cron/crontab.1", "systemd-cron/crontab.5", "systemd-cron/crontab.1"]]

If possible, some kind of typo-correction would also be useful (e.g., 'corn' should get results for 'cron').

I don't know what to do about exposing different suites or languages without causing a combinatorial explosion and bad UX.

**Comment by stapelberg** [comment]
Thanks, that’s a good suggestion. I briefly verified that opensearch suggestions are supported by Firefox and Chrome.

One open question is whether suggestions should match the beginning of the page name only (e.g. `dat` matches `date`) or anywhere in the page name (e.g. `dat` matches `updatedb` as well).

**Comment by stapelberg** [comment]
Side note: both Firefox and Chrome seem to only take the suggestions themselves, they ignore the descriptions and URLs.

**Comment by bucklereed** [comment]
I'd suggest only (fuzzy) prefix-matching; that's what Wikipedia, Wiktionary and YouTube do for suggestions and IME it works really well.

One other feature I've realised would be handy (but please feel free to punt if it'd be too annoying): if the input has a package or a section, that should be respected in the suggestions, and the package name should allow partial matches. So, using the crontab example:

cr/cron -> ["cr/cron", ["cron.8", "cron/crontab.5", "cron/crontab.1"]]
cron.5 -> ["cron.5", ["cron/crontab.5", "systemd-cron/crontab.5"]]

**Comment by stapelberg** [comment]
Pushed a commit to implement a suggestion endpoint. The change to the opensearch XML file should be live after the next re-run and mirror sync (within a day or so).

In order to keep the endpoint performant, I had to implement prefix-only matching for now. If people want matching within words and can contribute an efficient implementation, pull requests for that would be welcome.
