### ISSUE TITLE
about page has a weird bracket

### ISSUE THREAD

**Issue by anarcat** [Debian/debiman#73]
the [about page](https://manpages.debian.org/about.html) has a weird bracket in the middle:

![image](https://cloud.githubusercontent.com/assets/796623/25253688/fb9dd164-25ef-11e7-941d-b546760fb88b.png)

i'd fix it myself, but i can't find that in the about.tmpl page here and i can't find the debian-specific assets repo - isn't that public?

**Comment by stapelberg** [comment]
The repository with the debian-specific assets is https://anonscm.debian.org/git/srv-manpages/debian-assets.git/

**Comment by anarcat** [comment]
thanks, fixed in d940db5.
