### ISSUE TITLE
link to the man7.org project

### ISSUE THREAD

**Issue by anarcat** [Debian/debiman#74]
This guy apparently wrote hundreds of manpages and hosts a similar service. He deserves credit and linking:

https://www.kernel.org/doc/man-pages/

**Comment by stapelberg** [comment]
Given that we currently list other manpage repositories on our about page, I don’t mind having man7.org show up there as well.

As mentioned in the other issue, the repository in question is https://anonscm.debian.org/git/srv-manpages/debian-assets.git/, if you want to go ahead and just change the about page yourself :).

**Comment by anarcat** [comment]
Alright, thanks! I've linked to man7.org and made a few other changes to clarify the distinctions between the other manpages sites...
