### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by h4ck3rm1k3** [Debian/debiman#81]
listening to your talk, 
checked this for example : https://manpages.debian.org/experimental/nodejs/nodejs.1.en.html

links to : 404, the %0A causes a problem
https://groups.google.com/group/nodejs%0A
https://github.com/nodejs/node%0A
https://nodejs.org/api/%0A

**Comment by stapelberg** [comment]
Thanks. I’ll have a look at why this happens later today.

**Comment by stapelberg** [comment]
Pushed a commit to fix this. Will start re-rendering manpages.d.o now, so the fixes should be live by tomorrow.
