### ISSUE TITLE
will tests fail once stretch (or buster?) is released?

### ISSUE THREAD

**Issue by anarcat** [Debian/debiman#82]
looking at the redirection test suite, I can't help but think that it will start to fail once stretch comes out the door. tests like this:

```
		{Case: 9, URL: "stable/i3", want: "jessie/i3-wm/i3.1.en.html"},   // suite alias
```

will (should!) likely fail when stable becomes stretch.

i'm not sure how best to fix this, but it seems to me like a first step would be to avoid hardcoding the suite codenames into the tests, and use some sort of variable, which could eventually be automatically populated...

**Comment by stapelberg** [comment]
Thanks for bringing this up.

The tests will actually not fail because they use the hard-coded `testIdx` (defined above in the same file).

In production, debiman uses information from the archive directly and will hence use up-to-date names.
