### ISSUE TITLE
Please support serving in a subdirectory

### ISSUE THREAD

**Issue by bdrung** [Debian/debiman#86]
I want to serve the man pages in a subdirectory, e.g. http://example.com/man, but debiman creates absolute urls like `/stretch/sl/LS.6.de.html` instead of `/man/stretch/sl/LS.6.de.html` even if I specify `-base_url=http://example.com/man`

**Comment by stapelberg** [comment]
Thanks for the report. I’ll take a look later. Can you clarify on which pages specifically you noticed absolute URLs?

Also, out of curiosity, what’s your use-case? Are you converting an existing public manpage repository, starting a new, starting an internal one, …? :)

**Comment by bdrung** [comment]
Nearly all. The landing page, then click on "Browse the repository index", then click on a package. All these links are affected.

I evaluate debiman to use it for our inhouse Debian repository and wanted to service it as one subdirectory from our repository host. That way debiman has local file access to all packages.

I like to see bug #1 fixed.

PS: Thanks for codesearch.debian.net. That is a great tool, too.

**Comment by stapelberg** [comment]
This should now be fixed. Please let me know if I missed a spot. I can take a stab at #1 in a bit, but iterations will be a lot quicker if you just build from source for now :).

**Comment by bdrung** [comment]
Thanks. Most URLs are correct now.

`assets/style.css` points to font files in the top level (e.g. `/Inconsolata.woff`). This css file needs to be converted into a template.
