### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by lahwaacz** [Debian/debiman#90]
What are the permalinks intended for? For example if I go to https://manpages.debian.org/man.1, I'm redirected to the full URL (https://manpages.debian.org/stretch/man-db/man.1.en.html) so there is no need to include a permalink on the page.

On localized pages however, the permalink is not "permanent" at all, because it strips the language. For example, the permalink on https://manpages.debian.org/stretch/man-db/man.1.de.html is https://manpages.debian.org/stretch/man-db/man.1, which redirects to https://manpages.debian.org/stretch/man-db/man.1.en.html. Localized permalinks work only if the localized version is in different package than any other translation.

**Comment by stapelberg** [comment]
The permalink is indeed just a language-independent link for the manpage. If you prefer to reference a specific language directly, just use the URL.

**Comment by lahwaacz** [comment]
Why is it called "permalink" then?

**Comment by stapelberg** [comment]
Because it produces the most permanent link which still respects the user’s preferred language, and should be used in wikis, articles, etc.

**Comment by lahwaacz** [comment]
That's very different from the usual definition used by [Wikipedia](https://en.wikipedia.org/wiki/Permalink) and about every other project I know of. I'd call this simply a "language-independent link", which is exactly what the link does.

**Comment by stapelberg** [comment]
Changed it. This will be picked up on the next full re-rendering, which might be a while.
