### ISSUE TITLE
Are versions with different encodings served?

### ISSUE THREAD

**Issue by lahwaacz** [Debian/debiman#92]
This is just a question.

The [interesting test cases](https://github.com/Debian/debiman/#interesting-test-cases) section in the README says:

> [qelectrotech(1)](https://manpages.debian.org/stretch/qelectrotech/qelectrotech.1.en.html) has a french translation in 3 different encodings (none specified, ISO8859-1, UTF-8).

Is it just a test case for the import (in which case manpages.debian.org serves only one version per language) or should the different encodings be served as well? The whole section seems to describe test cases for the website and the URL scheme, but there are no links to the version with different encoding and the URL scheme does not seem to allow specifying an encoding.

In case only one version per language is served, which encoding is used as the source for the conversion to HTML? Do you actually check that all versions are in fact the same page encoded differently or is it just an assumption? After all the versions might go out-of-sync due to poor maintenance...

**Comment by stapelberg** [comment]
All manpages are converted to UTF-8 when ingesting. Manpages generally are present in precisely one encoding, so we don’t handle the case where multiple encodings are present.

**Comment by lahwaacz** [comment]
Thanks.
